In [3]:
import h
x=torch.rand(4)
x
torch.cuda.is_available()
### BASIC torch

randm2dvector=torch.empty(2,3)

ones2dvector=torch.ones(2,3)

zeros2dvector=torch.zeros(3,4)

randm2dvector,ones2dvector,zeros2dvector

ones2dvector=torch.ones(2,3,dtype=torch.double)
ones2dvector.dtype
x=torch.tensor([23,23,2,1,3])
x
y=torch.rand(2,3)
x=torch.rand(2,3)
x

y
x+y
torch.add(x,y)
y.add_(x)
y.add(x)
print(x-y)
print(torch.sub(x,y))
print(x.sub(y))
x
# element wise multiplication



print(x*y)
print(torch.mul(x,y))
print(x.mul(y))
print(x)
x[1,1].item()
x=torch.rand(4,4)
x.view(-1,16)# reshape


tensor([[-0.1304, -0.1987, -0.6146],
        [-0.8669, -0.8477, -0.1630]])
tensor([[-0.1304, -0.1987, -0.6146],
        [-0.8669, -0.8477, -0.1630]])
tensor([[-0.1304, -0.1987, -0.6146],
        [-0.8669, -0.8477, -0.1630]])
tensor([[0.0024, 0.2600, 1.5050],
        [1.6442, 0.7135, 0.2807]])
tensor([[0.0024, 0.2600, 1.5050],
        [1.6442, 0.7135, 0.2807]])
tensor([[0.0024, 0.2600, 1.5050],
        [1.6442, 0.7135, 0.2807]])
tensor([[0.0161, 0.4201, 0.9574],
        [0.9201, 0.5212, 0.4546]])


tensor([[0.9053, 0.4696, 0.0991, 0.9385, 0.9687, 0.2465, 0.8868, 0.5074, 0.1410,
         0.0609, 0.4089, 0.9892, 0.2514, 0.6203, 0.6474, 0.5095]])

In [16]:
import numpy as np
import torch
a=torch.ones(5)
print(a)
b=a.numpy()
print(type(b))
a.add_(4)
b
import numpy as np
import torch
a=np .ones(5)
print(a)
b=torch.from_numpy(a)
print(type(b))






tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>


In [35]:
import torch
x=torch.randn(3,requires_grad=True)
print(x)

tensor([ 0.0469, -0.6666,  0.3697], requires_grad=True)


In [36]:
y=x+2
z=y*y*2

print(z)

z=z.mean()

print(z)

tensor([ 8.3799,  3.5558, 11.2313], grad_fn=<MulBackward0>)
tensor(7.7223, grad_fn=<MeanBackward0>)


In [37]:

z.backward()
# x.grad

In [39]:
x.grad

print(z,x.grad)

tensor(7.7223, grad_fn=<MeanBackward0>) tensor([2.7292, 1.7778, 3.1597])
